### ISSUE TITLE
Brace-initialize values in the class definition

### ISSUE THREAD

**Issue by jcelerier** [thibaudk/dno#1]
https://github.com/thibaudk/dno/blob/95d6f3b9998f4d1db688f3838476d7f208a44f2e/include/1efilter.hpp#L43

e.g. 

  T xprev{};
  bool hadprev{};
  double freq{}, dcutoff{};

it's almost negligible in term of performance impact (sometimes it can even be faster if the compiler detects it can just memset(0) everything instead of doing it piecewise). And often saves a lot of bugs.

**Comment by thibaudk** [comment]
done with 6ddcc4c
