### ISSUE TITLE
Precompute constants as to never do divisions at runtime 

### ISSUE THREAD

**Issue by jcelerier** [thibaudk/dno#2]
https://github.com/thibaudk/dno/blob/95d6f3b9998f4d1db688f3838476d7f208a44f2e/include/1efilter.hpp#L65

e.g. save 1/dcutoff in the class instead of dcutoff (in setAlpha) and then: 

```

  void computeAlpha()
  {
    constexpr auto inv_2pi = 1. / (2 * M_PI); //(I think boost.math has it precomputed)
    T tau = inv_2pi * inv_dcutofff;

    double te = 1. / freq;

    alpha = 1.0 / (1.0 + tau / te);
  }
```

note that it's an optimization, the most important is to get it to work correctly first,; this is really not urgent =)

**Comment by thibaudk** [comment]
cutoff can be set at runtime, so dividing 1 by cutoff at runtime seems unavoidable.
But Boost does have 1 / half_pi precompiled, so it is used since 6ddcc4c
